### ISSUE TITLE
Search feature returns some tracks that don't have the icons/buttons row below track bar

### ISSUE THREAD

**Issue by Plex4000** [r-park/soundcloud-ngrx#14]
Soundcloud-ngrx version: 0.4.0
OS Version: Windows 10 Pro

When I search for songs or click on an artist's name,  sometimes the returned list of songs contains a track that is missing the row of icons below the track's waveform bar.  I am referring to the row of icons that include the play button, favorites count etc.

**Comment by r-park** [comment]
Hi @Plex4000 — some tracks on SoundCloud do not support streaming. The row of icons is not displayed for those tracks.
