### ISSUE TITLE
Faster compilation with fork-ts-checker

### ISSUE THREAD

**Issue by johnnyreilly** [r-park/soundcloud-ngrx#15]
Hey @r-park,

It was great to see your app demonstrated by @ahejlsberg at Build ❤️ 

I noticed that your app is using ts-loader with webpack.  I'm one of the maintainers of ts-loader and I thought you might be interested in speeding up your build.  If you are then you might want to check out the [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin).  Essentially this allows you to set `ts-loader` to run in `transpileOnly` mode and moves the type checking off to a separate process.  

What you get in return is much faster build times.  I can't claim any credit for this myself - it's all been the effort of @piotr-oles.  

If you'd like to see a simple example then check out: https://github.com/TypeStrong/ts-loader/blob/master/examples/fork-ts-checker/webpack.config.js

I do plan to blog about this at some point and spread the word a little more effectively.

PS Do feel free to close this issue - it's not really an issue at all; just wanted to give you a heads up.

**Comment by r-park** [comment]
Hey @johnnyreilly thanks for the heads-up 👍 I'll definitely take a look!

Cheers
