### ISSUE TITLE
Unable to play sound due to api loading fail.

### ISSUE THREAD

**Issue by yehe01** [r-park/soundcloud-ngrx#27]
<img width="448" alt="screen shot 2017-10-30 at 6 57 22 pm" src="https://user-images.githubusercontent.com/1256556/32160080-48172aee-bda4-11e7-8897-a0c6ceb4bd84.png">

Do I need to configure anything like API key?

<img width="696" alt="screen shot 2017-10-30 at 7 00 11 pm" src="https://user-images.githubusercontent.com/1256556/32160161-9b835c84-bda4-11e7-8b91-c09b857b67e2.png">

Detail response content is:

`{"errors":[{"meta":{"rate_limit":{"bucket":"by-client","max_nr_of_requests":15000,"time_window":"PT24H","name":"plays"},"remaining_requests":0,"reset_time":"2017/10/30 20:10:21 +0000"}}]}`

BTW, i am running in dev mode.

**Comment by r-park** [comment]
IIRC SoundCloud limits the number of requests/day for each API key. The [default API key](https://github.com/r-park/soundcloud-ngrx/blob/master/webpack.config.js#L25) provided in this repo is being over used. You can get your own API key via the SoundCloud Developer site.

**Comment by yehe01** [comment]
<img width="647" alt="screen shot 2017-11-06 at 1 41 24 pm" src="https://user-images.githubusercontent.com/1256556/32423029-33953846-c2f8-11e7-993b-9fdf8212a874.png">

Looks like soundcloud doesn't allow creating new apps any more.
Any idea on how to get a new API key?

**Comment by r-park** [comment]
AFAIK I think that's the only way. TBH I'm not sure how much longer SoundCloud is going to be around, or how much longer it will remain free.
