### ISSUE TITLE
What is the intention of not updating users state?

### ISSUE THREAD

**Issue by yehe01** [r-park/soundcloud-ngrx#28]
According to the test case `users-reducer.spec.ts`: 

`should NOT replace existing user if existing user is profile`

and the code https://github.com/r-park/soundcloud-ngrx/blob/9effe62d6b8a0278cd2375f41c97a625fe68cb83/src/app/users/state/users-reducer.ts#L29

Is it true that if a user's profile (https://soundcloud-ngrx.herokuapp.com/users/632699/tracks) has been visited once, new user data like numbers of likes, followers, following will never be updated again between navigations unless the user refresh the browser?

**Comment by r-park** [comment]
That `if` statement probably doesn't need to be there — there may have been a reason at one point but I don't recall. Looks like a simple merge/deep-merge should suffice.
